import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GradualBlurMemo from "@/components/reactBits/GradualBlur";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} pb-10 antialiased`}
      >
        {children}
        <GradualBlurMemo
          target="page"
          position="bottom"
          height="5rem"
          strength={2}
          divCount={10}
          curve="bezier"
          exponential={true}
          opacity={1}
        />
      </body>
    </html>
  );
}
